# Generated by Django 4.2 on 2026-05-25 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('manual', '手动'), ('upload', '文件上传'), ('api', 'API调用')], max_length=16, verbose_name='来源')),
                ('status', models.CharField(choices=[('success', '成功'), ('processing', '处理中'), ('failed', '失败')], default='success', max_length=16, verbose_name='状态')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='输入文件')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/%Y/%m/%d/', verbose_name='输出文件')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/%Y/%m/%d/', verbose_name='截图')),
                ('result_class', models.CharField(blank=True, max_length=16, verbose_name='预测类别ID')),
                ('result_label', models.CharField(blank=True, max_length=128, verbose_name='预测结果')),
                ('result_category', models.CharField(blank=True, max_length=64, verbose_name='大类')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('topk', models.JSONField(blank=True, null=True, verbose_name='TopK')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='附加信息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '识别记录',
                'verbose_name_plural': '识别记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recognitionrecord',
            index=models.Index(fields=['record_type', 'created_at'], name='recognition_record__5e9f70_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrecord',
            index=models.Index(fields=['status', 'created_at'], name='recognition_status_3448a6_idx'),
        ),
        migrations.AddIndex(
            model_name='recognitionrecord',
            index=models.Index(fields=['result_category', 'created_at'], name='recognition_result__4fcf69_idx'),
        ),
    ]
